/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft */
        post: operations["draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify */
        post: operations["classify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /**
             * Workspace Id
             * @description ID de l'espace de travail
             */
            workspace_id: string;
            /**
             * Tenant Id
             * @description ID du locataire pour enrichir le contexte
             */
            tenant_id?: string | null;
            /**
             * Messages
             * @description Historique de la conversation
             */
            messages: components["schemas"]["Message"][];
            /**
             * System Context
             * @description Contexte additionnel à injecter dans le prompt système
             */
            system_context?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /**
             * Reply
             * @description Réponse générée par l'IA
             */
            reply: string;
            /**
             * Model
             * @description Modèle utilisé
             */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /** ClassifyRequest */
        ClassifyRequest: {
            /**
             * Workspace Id
             * @description ID de l'espace de travail
             */
            workspace_id: string;
            /**
             * Message
             * @description Message entrant à classifier
             */
            message: string;
        };
        /** ClassifyResponse */
        ClassifyResponse: {
            /**
             * Category
             * @description Catégorie du message (maintenance, paiement, réclamation, etc.)
             */
            category: string;
            /**
             * Confidence
             * @description Score de confiance entre 0 et 1
             */
            confidence: number;
            /**
             * Summary
             * @description Résumé court du message
             */
            summary: string;
        };
        /** DraftRequest */
        DraftRequest: {
            /**
             * Workspace Id
             * @description ID de l'espace de travail
             */
            workspace_id: string;
            /**
             * Tenant Id
             * @description ID du locataire pour enrichir le contexte
             */
            tenant_id?: string | null;
            /**
             * Subject
             * @description Sujet du message à rédiger
             */
            subject: string;
            /**
             * Context
             * @description Contexte pour la rédaction (infos locataire, situation, etc.)
             */
            context: string;
            /**
             * Recipient Name
             * @description Nom du destinataire
             */
            recipient_name?: string | null;
            /**
             * Tone
             * @description Ton du message
             * @default formal
             * @enum {string}
             */
            tone: "formal" | "friendly" | "neutral";
        };
        /** DraftResponse */
        DraftResponse: {
            /**
             * Draft
             * @description Brouillon de message rédigé
             */
            draft: string;
            /**
             * Subject
             * @description Objet du message
             */
            subject: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** Message */
        Message: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
